### ISSUE TITLE
To-do list de fin de projet

### ISSUE THREAD

**Issue by aitam-r** [aitam-r/projet_base_prog#7]
Les faciles
- [ ] Changer tous les nom getplat, setplat, makepos, dansplat etc... en get_plat, set_plat etc... (ne pas oublier de tous les changer)
- [ ] Remplacer les accès plateaux (ep->plateau.... et ep.plateau...) par des get_plat et set_plat
- [ ] Créer une fonction qui affiche le gagnant (vainqueur_disp) plus proprement. Elle serait appelée dans kuba (à la fin)
- [ ] Les fonctions qui ne modifient pas des valeurs passées par référence (avec des pointeurs quoi) rajoutent des const (ex : const etat_plat *ep)
- [ ] Mettre des do {} while(...) autour de chaque saisie utilisateur

Les plus durs
- [ ] Créer une fonction initialiser plateau plus générique, qui fasse appel au joueur, ou pas
- [ ] Créer des fonctions x_disp (erreur_disp, joueur_disp...) qui fasse appel aux statics char comme dans son mail
- [ ] créer une structure comme state dans son mail qui rassemble les infos sur les pions rouges gagnés et les pions de couleur joueur restant

Galères
- [ ] Uniquement après avoir remplacé tous les accès plateaux : "tricher" comme dans tp9 et représenter le plateau juste comme un tableau à une dimension : contenu *plateau : il faut alors modifier get_plat, set_plat, (mais aussi allouer proprement ce tableau avec un malloc? Pas sûr que ce soit nécesaire)

Optionel
- [ ] Ecrire une IA moins conne avec l'algo minimax
